execute pathogen#infect()
syntax enable

autocmd FileType gradle setlocal shiftwidth=2 tabstop=2

" color scheme patine can be found at https://github.com/Canop/patine
colorscheme patine

filetype plugin indent on

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_custom_ignore = 'node_modules\|\.git\|static\|build|\*\.concat'
let mapleader=","

set incsearch
set hlsearch
nnoremap <CR> :nohlsearch<CR><CR>
nnoremap i :nohlsearch<CR>i
nnoremap c :nohlsearch<CR>c
nnoremap a :nohlsearch<CR>a

set t_Co=256

let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1


" console.log word under cursor
nmap <Leader>cl yiwoconsole.log('<c-r>":', <c-r>");<Esc>^

" ensures there's at least 5 lines visible around the current one
set so=5

" diff unsaved vs saved file
nnoremap <Leader>do :DiffOrig<cr>

set showcmd

" to enable char marks instead of line marks
" Build mark a: ma
" Go to mark a : 'a
nnoremap ' `

" display current markdown file as HTML in browser
" (grip must be installed)
nmap <Leader>md <Esc>:!grip -b %<CR><CR>

" surround current (w|W)ord with quotes or code marks
nnoremap <Leader>k ciw``<Esc>P
vnoremap <Leader>k :s/\%V\(.*\)\%V/`\1`/<Esc>
nnoremap <Leader>q ciw""<Esc>P
vnoremap <Leader>q :s/\%V\(.*\)\%V/"\1"/<Esc>
nnoremap <Leader>K ciW``<Esc>P
nnoremap <Leader>Q ciW""<Esc>P

" gp selects the last selection
nnoremap gp `[v`]

" open a file in current file's directory
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>
map <Leader>s :split <C-R>=expand("%:p:h") . "/" <CR>

" prevent accidentally entering ex mode
map q: <Nop>
nnoremap Q <nop>

" speed up searches in node projects
set wildignore+=**/node_modules/**

" jk or kj in insert mode exit the insert mode
imap jk <C-[>
imap kj <C-[>

" easier buffer switching
nnoremap <Tab> :b#<CR>

nnoremap <Leader>p :<C-u>CtrlP<CR>
nnoremap <Leader>b :<C-u>CtrlPBuffer<CR>
nnoremap <Leader>r :<C-u>CtrlPMRU<CR>

inoremap {      {}<Left>
inoremap {<CR>  {<CR>}<Esc>O
inoremap {{     {
inoremap {}     {}
