execute pathogen#infect()
syntax enable

autocmd FileType gradle setlocal shiftwidth=2 tabstop=2

set undofile
set undodir=$HOME/.vim/undo

" color scheme patine can be found at https://github.com/Canop/patine
colorscheme patine

filetype plugin indent on

" fzf, installed through vim-plug
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
" Plug 'junegunn/fzf.vim'

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_max_files=0
let g:ctrlp_custom_ignore = 'node_modules\|\.git\|static\|build|\*\.concat'

let mapleader="\<space>"

" Eliminate delay when switching modes
set ttimeoutlen=0

set updatetime=250

set incsearch
set hlsearch
nnoremap <CR> :nohlsearch<CR><CR>
nnoremap i :nohlsearch<CR>i
nnoremap c :nohlsearch<CR>c
nnoremap a :nohlsearch<CR>a

set t_Co=256

" for vim-airline
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_theme='distinguished'
" disable mix-indent-file check (too buggy)
let g:airline#extensions#whitespace#checks = [ 'indent', 'trailing', 'long']

let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1

" console.log word under cursor
nmap <Leader>cl yiwoconsole.log('<c-r>":', <c-r>");<Esc>^
nmap <Leader>cL yiwOconsole.log('<c-r>":', <c-r>");<Esc>^

" ensures there's at least 5 lines visible around the current one
set so=5

" diff unsaved vs saved file
command DiffOrig let g:diffline = line('.') | vert new | set bt=nofile | r # | 0d_ | diffthis | :exe "norm! ".g:diffline."G" | wincmd p | diffthis | wincmd p
nnoremap <Leader>do :DiffOrig<cr>
nnoremap <leader>dc :q<cr>:diffoff<cr>:exe "norm! ".g:diffline."G"<cr>

set showcmd

" to enable char marks instead of line marks
" Build mark a: ma
" Go to mark a : 'a
nnoremap ' `


" display current markdown file as HTML in browser
" (grip must be installed)
nmap <Leader>md <Esc>:!grip -b %<CR><CR>

" markdown edition:
" surround current (w|W)ord with quotes or code marks
nnoremap <Leader>k ciw``<Esc>P
vnoremap <Leader>k :s/\%V\(.*\)\%V/`\1`/<Esc>
nnoremap <Leader>q ciw""<Esc>P
vnoremap <Leader>q :s/\%V\(.*\)\%V/"\1"/<Esc>
nnoremap <Leader>K ciW``<Esc>P
nnoremap <Leader>Q ciW""<Esc>P

" gp selects the last selection
nnoremap gp `[v`]

" open a file in current file's directory
map <Leader>e :w<CR>:e <C-R>=expand("%:p:h") . "/" <CR>
map <Leader>s :split <C-R>=expand("%:p:h") . "/" <CR>

" find current word in current (adjustable) directory
map <Leader>f :w<CR>yiw:vim /\<<C-R>"\>/ <C-R>=expand("%:p:h") . "/" <CR>

" find current word in current directory
map <Leader>ff :w<CR>yiw:vim /\<<C-R>"\>/ <C-R>=expand("%:p:h") . "/*" <CR><CR>

" prevent accidentally entering ex mode
map q: <Nop>
nnoremap Q <nop>

" speed up searches in node projects
set wildignore+=**/node_modules/**
set wildignore+=**/build/**
set wildignore+=*.class,*.so

" Auto save changes before switching buffer
set autowrite

" Keep the cursor in the same place when switching buffers
set nostartofline

" easier buffer switching
nnoremap <Tab> :w<CR>:b#<CR>
nnoremap <C-Tab> :w<CR>:b3<CR>
" shows the list of buffers and let you choose one
nnoremap <leader>b :w<CR>:buffers<CR>:buffer<space>

" adds an empty line before the current one (don't make it a comment line if
" the current one is commented)
nmap OO ko<Esc>j
" adds an empty line below the current one
nmap oo o<Esc>k

" Delete line but preserve the space
nnoremap dD S<Esc>

" Make `Y` work from the cursor to the end of line
nnoremap Y y$

" Use K to join current line with line above, just like J does with line below
nnoremap K kJ

"Switch to current dir
nnoremap <Leader>cd :cd %:p:h<cr>

" I always go to that file...
nmap <Leader>t :e ~/todo.txt<CR>

" remove trailing spaces on save
autocmd BufWritePre *.py,*.js,*.txt,*.md,*.hs,*.rs,*.html,*.css,*.less,*.scss,*.java :%s/\s\+$//e

"set cursorline

set wildmenu " file autocompletion menu

" move vertically by visual line (for wrapped lines)
nnoremap j gj
nnoremap k gk

" :w!! 
" write the file when you accidentally opened it without the right (root) privileges
" Courtesy CIA ( https://wikileaks.org/ciav7p1/cms/page_4849889.html )
cmap w!! w !sudo tee % > /dev/null

" indent/dedent shortcut for the current line
nmap < V<
nmap > V>

" Shortcuts relevant for my current projects
noremap <Leader>i :w<CR>:!./install.sh<CR>
noremap <Leader>me :w<CR>:e ~/dev/miaou/
